version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:8080"
    volumes:
      - ./:/app
  db:
    image: postgres:15.1-alpine
    ports:
      - "5454:5432"
    restart: always
    environment:
      POSTGRES_USER: skif
      POSTGRES_PASSWORD: Aa123123
      POSTGRES_DB: testApp
    volumes:
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

